### ISSUE TITLE
HA 2026.6.0b0 ImportError: cannot import name 'ATTR_MODE' from homeassistant.components.text.const

### ISSUE THREAD

**Issue by davesimon21** [make-all/tuya-local#5182]
### Description

**Environment**

- Home Assistant: 2026.6.0b0
- tuya_local: 2026.5.4
- Installation method: HACS
- Python: 3.14 (from HA container)

**Description**

After upgrading Home Assistant to 2026.6.0b0, several tuya_local devices fail to initialize.

The affected devices appear to be devices exposing the text platform.

Other tuya_local devices continue functioning normally.

**Error**
```
Logger: homeassistant.config_entries
Source: config_entries.py:794

Error setting up entry Tower 5 Top for tuya_local

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 794, in __async_setup_with_context
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/tuya_local/__init__.py", line 965, in async_setup_entry
    await hass.config_entries.async_forward_entry_setups(entry, entities)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 2739, in async_forward_entry_setups
    await integration.async_get_platforms(platforms)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1312, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
  File "/config/custom_components/tuya_local/text.py", line 8, in <module>
    from homeassistant.components.text.const import (
ImportError: cannot import name 'ATTR_MODE' from 'homeassistant.components.text.const'
```

### Additional context

This appears related to a Home Assistant 2026.6 beta API change involving `homeassistant.components.text.const`.

Potentially related to removal/renaming of `ATTR_MODE`.

I have confirmed:

- running latest tuya_local release (2026.5.4)
- restart does not resolve issue
- only some devices are affected
- issue began immediately after upgrading to HA 2026.6.0b0

### Confirmation

- [x] I am sure this is a bug or improvement, that is well enough described that it can be implemented.
- [x] This report is for make-all/tuya-local, **not** for localtuya, a modified tuya-local not from make-all, the Tuya app or cloud.
- [x] The device this issue is about is externally powered, or connecting via a hub (battery powered WiFi devices are NOT supported by this integration).
- [x] I have checked the latest released version of tuya-local
- [ ] If this is for a specific device, the device config filename is mentioned above, or diagnostics are included.

- [ ] Log messages or diagnostics relevant to the issue are included.

- [x] This is not requesting addition of a new device.

**Comment by Mikefila** [comment]
Additional log

Logger: homeassistant.util.loop
Source: util/loop.py:135
First occurred: 4:52:08 PM (1 occurrence)
Last logged: 4:52:08 PM

Detected blocking call to import_module with args ('custom_components.tuya_local.text',) inside the event loop by custom integration 'tuya_local' at custom_components/tuya_local/__init__.py, line 965: await hass.config_entries.async_forward_entry_setups(entry, entities) (offender: /usr/src/homeassistant/homeassistant/loader.py, line 1312: return importlib.import_module(f"{self.pkg_path}.{platform_name}")), please create a bug report at https://github.com/make-all/tuya-local/issues For developers, please see https://developers.home-assistant.io/docs/asyncio_blocking_operations/#import_module Traceback (most recent call last): File "<frozen runpy>", line 203, in _run_module_as_main File "<frozen runpy>", line 88, in _run_code File "/usr/src/homeassistant/homeassistant/__main__.py", line 227, in <module> sys.exit(main()) File "/usr/src/homeassistant/homeassistant/__main__.py", line 213, in main exit_code = runner.run(runtime_conf) File "/usr/src/homeassistant/homeassistant/runner.py", line 289, in run return loop.run_until_complete(setup_and_run_hass(runtime_config)) File "/usr/local/lib/python3.14/asyncio/base_events.py", line 706, in run_until_complete self.run_forever() File "/usr/local/lib/python3.14/asyncio/base_events.py", line 677, in run_forever self._run_once() File "/usr/local/lib/python3.14/asyncio/base_events.py", line 2057, in _run_once handle._run() File "/usr/local/lib/python3.14/asyncio/events.py", line 94, in _run self._context.run(self._callback, *self._args) File "/usr/src/homeassistant/homeassistant/config_entries.py", line 963, in async_setup_locked await self.async_setup(hass, integration=integration) File "/usr/src/homeassistant/homeassistant/config_entries.py", line 700, in async_setup await self.__async_setup_with_context(hass, integration) File "/usr/src/homeassistant/homeassistant/config_entries.py", line 794, in __async_setup_with_context result = await component.async_setup_entry(hass, self) File "/config/custom_components/tuya_local/__init__.py", line 965, in async_setup_entry await hass.config_entries.async_forward_entry_setups(entry, entities)`
